# Generated by Django 2.1.15 on 2021-04-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QQNum', models.IntegerField()),
                ('Nick', models.CharField(max_length=80)),
                ('Age', models.IntegerField()),
                ('Gender', models.IntegerField()),
                ('Auth', models.IntegerField()),
                ('QunNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QunNum', models.IntegerField()),
                ('MastQQ', models.IntegerField()),
                ('CreateDate', models.CharField(max_length=10)),
                ('Title', models.CharField(max_length=22)),
                ('Class', models.CharField(max_length=38)),
                ('QunText', models.CharField(max_length=80)),
            ],
        ),
    ]
